### PR TITLE
Fix issue with displaying images in email

### PR DESCRIPTION
**Pull request by SonaliChavan95**
Hello @team,
This PR fixes issues of displaying images in a notification email of posting a new article. Please review it and let me know if any changes are required. 

Trello: [Images present in post are shown as broken images in the email message](https://trello.com/c/svtxxSsU/62)

Thank you

### CODE REVIEW

**Comment by rohandaxini** [comment]
@SonaliChavan95 Did you finalise this PR, fixed merge conflicts on your local and tested ?
I want to move this ahead in Jan-2017. Let me know when we can finalise this PR?
Refer my old commit as well to fix bugs and pass specs.

**Comment by rohandaxini** [comment]
@sampatbadhe @punitcse Refer my above comment to @SonaliChavan95 and my old commits. We want to move this ahead in Jan-2018 itself. Request you to collaborate with @SonaliChavan95 and finalise.

**Comment by SonaliChavan95** [comment]
Hello @rohandaxini 
I did not get time to take a look at this PR. I will solve the merge conflicts and test it on my local by next wednesday. I will also refer your old commits and will let you know once I am done.

cc: @sampatbadhe, @punitcse

**Comment by rohandaxini** [comment]
Okay let me know @SonaliChavan95 plans for it and we can discuss? You can estimate effort it will take and we can discuss allocation accordingly. We absolutely want to prepare this PR in Jan-2018 itself. cc: @varunlalan

**Comment by SonaliChavan95** [comment]
Hello @rohandaxini, @sampatbadhe, @punitcse 
I have solved the merge conflicts in this branch. Also, fixed the bug that I got after the code refactoring. Please review.

**Comment by SonaliChavan95** [comment]
Sure @sampatbadhe

**Comment by rohandaxini** [comment]
@sampatbadhe @SonaliChavan95 @punitcse Can you all discuss and come up with a date to finalise this PR? Accordingly I will test it on local and merge for PR.
**NOTE: We want to make sure this goes ahead in Jan-2018 itself.**

**Pull request merged**
