### PR TITLE
Comment spec of sign up feature

### PR DESCRIPTION
**Pull request by SupriyaMedankar**
Hello @team,
   In this PR I have commented spec of sign up feature as we have made it un-available. Please review it and let me know if any changes are required.

Trello ticket: https://trello.com/c/5czD0HMW/65

Thank you

### CODE REVIEW

**Comment by punitcse** [comment]
@SupriyaMedankar instead of commenting whole file you can simply change `scenario` to `xscenario` then it will be considered as pending test cases.

I am not very sure why do we need if we made signup feature unavailable. Can we remove the spec file?

**Comment by rohandaxini** [comment]
Hi @punitcse and @SupriyaMedankar We have temporarily disabled sign up feature for now. We can comment the scenario for now.

**Comment by rohandaxini** [comment]
@SupriyaMedankar we can use this to skip entire block of spec for now.

skip "is skipped" do
    ---
end

**Comment by rohandaxini** [comment]
@SupriyaMedankar 

```
scenario 'add activity for users signup' do
    skip "is skipped" do
      visit '/users/sign_up'

      fill_in 'user[name]', with: 'John'
      fill_in 'user[email]', with: 'user@example.com'
      fill_in 'user[password]', with: 'password'
      fill_in 'user[password_confirmation]', with: 'password'

      click_on 'Sign up'

      expect(page).to have_content 'You have signed up successfully.'

      expect(User.last.activities.count).to eq 1
      expect(page).to have_selector('.block2', text: 'John just joined KnowBuddy.')
    end
  end
```

**Pull request closed without merging**
