### PR TITLE
Fix issue draft running infinitely when emoji present in post

### PR DESCRIPTION
**Pull request by SupriyaMedankar**
Hello @team,
  This PR is about fix issue draft running infinitely when emoji present in post. The issue is occurring due to utf8 not supporting emoji string format. I have changed encoding format to utf8mb4. Please review it and let me know if any changes are required.

We need to add following setting in my.cnf file of mysql

default-storage-engine=InnoDB
innodb_file_format=barracuda
innodb_file_per_table=1
innodb_large_prefix=1
init_connect='SET collation_connection = utf8mb4_unicode_ci'
init_connect='SET NAMES utf8mb4'
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci

Trello ticket: https://trello.com/c/Ef7Giwum/61

Thank you 
  
PS: Please verify whether specs are getting pass after making changes in my.cnf

### CODE REVIEW

**Comment by rohandaxini** [comment]
@SupriyaMedankar Seems build is failing on this PR?
Did you every finalise it - as this is open since long time.
We need to plan this PR and move it ahead in Jan-2018

**Comment by rohandaxini** [comment]
@sampatbadhe @punitcse Refer my above comment to @SupriyaMedankar. We want to move this ahead in Jan-2018 itself. Request you to collaborate with @SupriyaMedankar  and finalise.

**Comment by SupriyaMedankar** [comment]
Hello @rohandaxini ,
We need to make changes in `my.cnf` file to make the build pass. I have put the required settings that need to be added to `my.cnf` file in PR description. I have also added steps to deploy this changes on the ticket, here:
https://trello.com/c/Ef7Giwum/61-post-save-as-draft-is-running-infinitely-if-we-have-emoji-in-the-content#comment-59ca10ed45d1f7146bad7c95

cc: @sampatbadhe, @punitcse

**Comment by sampatbadhe** [comment]
Hello @SupriyaMedankar 

https://gist.github.com/kamipo/8f0e9f3a985fe9f518e7
Refer above gist to add `my.cnf` file in circleci. let me know if any help required. 

cc: @punitcse

**Comment by rohandaxini** [comment]
So whats the next step on this @SupriyaMedankar @sampatbadhe ?
FYI...We absolutely want to prepare this PR in Jan-2018 itself. cc: @varunlalan

**Comment by SupriyaMedankar** [comment]
@rohandaxini , We have to add `circle.yml` file in the app to add `my.cnf` file with the required setting. I went through the link that @sampatbadhe has attached in his above comment. It is little difficult for me to understand as I have never did this type of setting. I will check it one more time and will add that to our app.
cc: @sampatbadhe

**Comment by SupriyaMedankar** [comment]
@team, I will complete this task by next thursay, I have changes due date on ticket.

**Comment by rohandaxini** [comment]
@SupriyaMedankar  Thats helpful, thanks. Let me know once ready and I will test it on local so thay we can merge this PR for PROD.
**NOTE: We want to make sure this goes ahead in Jan-2018 itself.**

**Comment by SupriyaMedankar** [comment]
Hello @team,
Spec fixed by taking the master pull. I have not added circle.yml file. I think we will not be required to make setting in `my.cnf` file. Still, want to test it once. @sampatbadhe or @punitcse can you please verify if this migration is running on your local without making any changes in `my.cnf` file.

**Comment by sampatbadhe** [comment]
Sure @SupriyaMedankar I'll check and let you know.

cc: @punitcse @rohandaxini

**Comment by sampatbadhe** [comment]
Hello @SupriyaMedankar 

I have tested this changes on my local I am able to create the post with smileys and the issue which reported is fixed. 

screen shot 2018-01-25 at 9 46 20 am

But I found that Migration is irreversible.

> SampatBadhes-MacBook-Pro:knowbuddy kiprosh-pico$ bundle exec rake db:rollback
> == 20170921055550 ChangeToUtf8mbEncoding: reverting ===========================
> rake aborted!
> StandardError: An error has occurred, all later migrations canceled:
> 
> ActiveRecord::IrreversibleMigration/Users/kiprosh-pico/projects/rails/inhouse-app/knowbuddy/db/migrate/20170921055550_change_to_utf8mb_encoding.rb:16:in `change'
> /Users/kiprosh-pico/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
> /Users/kiprosh-pico/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
> ActiveRecord::IrreversibleMigration: ActiveRecord::IrreversibleMigration
> /Users/kiprosh-pico/projects/rails/inhouse-app/knowbuddy/db/migrate/20170921055550_change_to_utf8mb_encoding.rb:16:in `change'
> /Users/kiprosh-pico/.rbenv/versions/2.2.2/bin/bundle:23:in `load'
> /Users/kiprosh-pico/.rbenv/versions/2.2.2/bin/bundle:23:in `<main>'
> Tasks: TOP => db:rollback
> (See full trace by running task with --trace)
> 

We have to write reversible migration which is a good practice. Can you please correct the migration?

**NOTE :** Event though we write reversible migration in future if we rollback migration and any of the post contains any post with `utf8mb4` characters(Smileys...) in that case we manually need to remove those characters and then rollback the migration. 

cc: @punitcse @rohandaxini

**Comment by SupriyaMedankar** [comment]
@sampatbadhe,
Thank you for the suggestion. I will add a reversible migration.

**Comment by SupriyaMedankar** [comment]
@sampatbadhe,
  Added reversible migration with removing emoji from the post while reverting migration. Please review.

cc: @punitcse, @rohandaxini

**Comment by sampatbadhe** [comment]
@SupriyaMedankar 

Migration looks good to me 👍 

 I will test it on my local tomorrow and will approve the PR accordingly. 

cc: @punitcse @rohandaxini

**Comment by sampatbadhe** [comment]
Hello @SupriyaMedankar 

I have verified the migration on local, working fine for me :+1:

cc: @rohandaxini @punitcse

**Comment by rohandaxini** [comment]
@SupriyaMedankar I deployed these changes to PROD today.
1. Modified my.conf for mysql and add the settings you mentioned above in PR description. All other lines are working fine for the configuration except `collation-server=utf8mb4_unicode_c`. 
When I add `collation-server=utf8mb4_unicode_c` to `[mysqld]` section of `/etc/mysql/my.cnf` then mysql server fails to restart and crashes.

2. After doing step-1 above by commenting line `collation-server=utf8mb4_unicode_c` I executed migrations and they ran fine. Seems you missed `PROD Chores` in Trello ticket to explicitly mention running migrations.

Could you please test PROD app now ?

cc: @sampatbadhe

**Comment by rohandaxini** [comment]
@SupriyaMedankar seems we still have issue in PROD. I tried one sample article with emoji and these are the errors in log file.

```

ActiveRecord::StatementInvalid (Mysql2::Error: Incorrect string value: '\xF0\x9F\x91\x8D \xF0...' for column 'content' at row 1: UPDATE `posts` SET `content` = 'trial task with emojis 👍 😄 💯 \r\ntrial task with emojis 👍 😄 💯 \r\ntrial task with emojis 👍 😄 💯 ', `slug` = 'testing-an-article-with-emoji-s-please-ignore', `is_draft` = 0, `is_published` = 1, `publish_at` = '2018-05-19 15:02:23', `updated_at` = '2018-05-19 15:02:23' WHERE `posts`.`id` = 2342):
  app/models/concerns/post_tags.rb:14:in `create_new_tag_activity'
  app/controllers/posts_controller.rb:57:in `create'


Started POST "/posts/draft" for 223.229.171.245 at 2018-05-19 11:02:42 -0400
Processing by PostsController#draft as JSON
  Parameters: {"post"=>{"id"=>"2342", "subject"=>"Testing an article with Emoji's - please ignore", "content"=>"trial task with emojis 👍 😄 💯 \ntrial task with emojis 👍 😄 💯 \ntrial task with emojis 👍 😄 💯 ", "user_id"=>"2", "tag_list"=>"", "is_draft"=>"true", "is_internal"=>"false"}, "attachments_field"=>""}
Completed 500 Internal Server Error in 28ms (ActiveRecord: 2.9ms)

ActiveRecord::StatementInvalid (Mysql2::Error: Incorrect string value: '\xF0\x9F\x91\x8D \xF0...' for column 'content' at row 1: UPDATE `posts` SET `content` = 'trial task with emojis 👍 😄 💯 \ntrial task with emojis 👍 😄 💯 \ntrial task with emojis 👍 😄 💯 ', `updated_at` = '2018-05-19 15:02:42' WHERE `posts`.`id` = 2342):
  app/models/concerns/post_tags.rb:14:in `create_new_tag_activity'
  app/controllers/posts_controller.rb:111:in `draft'
```

**Comment by rohandaxini** [comment]
Output of migrations
```
== 20170921055550 ChangeToUtf8mbEncoding: migrating ===========================
-- execute("ALTER DATABASE `knowbuddy_prod` CHARACTER SET utf8mb4\n      COLLATE utf8mb4_unicode_ci;")
   -> 0.0010s
-- execute("ALTER TABLE `active_admin_comments` ROW_FORMAT=DYNAMIC CHARACTER SET\n        utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0172s
-- execute("ALTER TABLE `active_admin_comments` MODIFY `resource_id` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  NOT NULL;")
   -> 0.0101s
-- execute("ALTER TABLE `active_admin_comments` MODIFY `resource_type` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  NOT NULL;")
   -> 0.0089s
-- execute("ALTER TABLE `active_admin_comments` MODIFY `author_type` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0084s
-- execute("ALTER TABLE `active_admin_comments` MODIFY `body` TEXT\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0103s
-- execute("ALTER TABLE `active_admin_comments` MODIFY `namespace` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0095s
-- execute("ALTER TABLE `activities` ROW_FORMAT=DYNAMIC CHARACTER SET\n        utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.2168s
-- execute("ALTER TABLE `activities` MODIFY `trackable_type` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.2315s
-- execute("ALTER TABLE `activities` MODIFY `owner_type` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.2480s
-- execute("ALTER TABLE `activities` MODIFY `key` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.1931s
-- execute("ALTER TABLE `activities` MODIFY `parameters` TEXT\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.1921s
-- execute("ALTER TABLE `activities` MODIFY `recipient_type` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.1672s
-- execute("ALTER TABLE `activity_types` ROW_FORMAT=DYNAMIC CHARACTER SET\n        utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0068s
-- execute("ALTER TABLE `activity_types` MODIFY `activity_type` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0058s
-- execute("ALTER TABLE `admin_users` ROW_FORMAT=DYNAMIC CHARACTER SET\n        utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0073s
-- execute("ALTER TABLE `admin_users` MODIFY `email` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  NOT NULL;")
   -> 0.0083s
-- execute("ALTER TABLE `admin_users` MODIFY `encrypted_password` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  NOT NULL;")
   -> 0.0066s
-- execute("ALTER TABLE `admin_users` MODIFY `reset_password_token` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0068s
-- execute("ALTER TABLE `admin_users` MODIFY `current_sign_in_ip` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0072s
-- execute("ALTER TABLE `admin_users` MODIFY `last_sign_in_ip` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0072s
-- execute("ALTER TABLE `attachments` ROW_FORMAT=DYNAMIC CHARACTER SET\n        utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0112s
-- execute("ALTER TABLE `attachments` MODIFY `attachable_file_name` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0107s
-- execute("ALTER TABLE `attachments` MODIFY `attachable_content_type` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0136s
-- execute("ALTER TABLE `attachments` MODIFY `context_type` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0126s
-- execute("ALTER TABLE `comments` ROW_FORMAT=DYNAMIC CHARACTER SET\n        utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0153s
-- execute("ALTER TABLE `comments` MODIFY `comment` TEXT\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0157s
-- execute("ALTER TABLE `posts` ROW_FORMAT=DYNAMIC CHARACTER SET\n        utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.1600s
-- execute("ALTER TABLE `posts` MODIFY `subject` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.1361s
-- execute("ALTER TABLE `posts` MODIFY `content` TEXT\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.1307s
-- execute("ALTER TABLE `posts` MODIFY `slug` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.1069s
-- execute("ALTER TABLE `posts` MODIFY `url_token` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.1257s
-- execute("ALTER TABLE `rule_engines` ROW_FORMAT=DYNAMIC CHARACTER SET\n        utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0077s
-- execute("ALTER TABLE `rule_engines` MODIFY `rule` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  NOT NULL;")
   -> 0.0074s
-- execute("ALTER TABLE `rule_engines` MODIFY `rule_for` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0077s
-- execute("ALTER TABLE `rule_engines` MODIFY `frequency` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0096s
-- execute("ALTER TABLE `rule_engines` MODIFY `schedule` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0104s
-- execute("ALTER TABLE `rule_engines` MODIFY `subject` TEXT\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0091s
-- execute("ALTER TABLE `rule_engines` MODIFY `body` TEXT\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0091s
-- execute("ALTER TABLE `rule_engines` MODIFY `max_duration` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0071s
-- execute("ALTER TABLE `schema_migrations` ROW_FORMAT=DYNAMIC CHARACTER SET\n        utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0069s
-- execute("ALTER TABLE `schema_migrations` MODIFY `version` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  NOT NULL;")
   -> 0.0069s
-- execute("ALTER TABLE `sendgrid_email_events` ROW_FORMAT=DYNAMIC CHARACTER SET\n        utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.1571s
-- execute("ALTER TABLE `taggings` ROW_FORMAT=DYNAMIC CHARACTER SET\n        utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0492s
-- execute("ALTER TABLE `taggings` MODIFY `taggable_type` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0513s
-- execute("ALTER TABLE `taggings` MODIFY `tagger_type` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0537s
-- execute("ALTER TABLE `taggings` MODIFY `context` VARCHAR(128)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0536s
-- execute("ALTER TABLE `tags` ROW_FORMAT=DYNAMIC CHARACTER SET\n        utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0204s
-- execute("ALTER TABLE `tags` MODIFY `name` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0251s
-- execute("ALTER TABLE `users` ROW_FORMAT=DYNAMIC CHARACTER SET\n        utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0124s
-- execute("ALTER TABLE `users` MODIFY `email` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  NOT NULL;")
   -> 0.0133s
-- execute("ALTER TABLE `users` MODIFY `encrypted_password` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  NOT NULL;")
   -> 0.0130s
-- execute("ALTER TABLE `users` MODIFY `reset_password_token` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0142s
-- execute("ALTER TABLE `users` MODIFY `current_sign_in_ip` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0247s
-- execute("ALTER TABLE `users` MODIFY `last_sign_in_ip` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0143s
-- execute("ALTER TABLE `users` MODIFY `name` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0457s
-- execute("ALTER TABLE `users` MODIFY `about` TEXT\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0135s
-- execute("ALTER TABLE `votes` ROW_FORMAT=DYNAMIC CHARACTER SET\n        utf8mb4 COLLATE utf8mb4_unicode_ci;")
   -> 0.0268s
-- execute("ALTER TABLE `votes` MODIFY `votable_type` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0324s
-- execute("ALTER TABLE `votes` MODIFY `voter_type` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0234s
-- execute("ALTER TABLE `votes` MODIFY `vote_scope` VARCHAR(255)\n      CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci  ;")
   -> 0.0233s
== 20170921055550 ChangeToUtf8mbEncoding: migrated (2.8908s) ==================
```

cc: @sampatbadhe @SupriyaMedankar

**Comment by rohandaxini** [comment]
@SupriyaMedankar I deployed these changes to PROD today.
1. Modified my.conf for mysql and added the settings you mentioned above in PR description. All other lines are working fine for the configuration and even this worked now `collation-server=utf8mb4_unicode_ci`.
 
Its my bad that I copy pasted it as `collation-server=utf8mb4_unicode_c` instead of `collation-server=utf8mb4_unicode_ci` i.e. missed character `i`.
Then I read the documentation and corrected it in my.cnf. Mysql Server restarted fine then.

2. After doing step-1 above by commenting line `collation-server=utf8mb4_unicode_c` I executed migrations and they ran fine. Seems you missed `PROD Chores` in Trello ticket to explicitly mention running migrations.

3. Now I tried posting a sample post with emoji's. App accepted the emoji's but after I check my submitted post then it looks like this screenshot.

screen shot 2018-05-19 at 8 46 28 pm

@sampatbadhe @sampatbadhe 
Do I need to rollback last migration and run migrations again after correcting the `my.cnf`

Could you please test PROD app now ?

**Comment by rohandaxini** [comment]
@sampatbadhe @SupriyaMedankar 

screen shot 2018-05-20 at 11 09 23 am

I have made few more settings on mysql database server on prod and re-verified that we have appropriate values for `character_set` and `collation` as `utf8mb4` everywhere. Refer screenshot above.

Then I created a script to alter all tables and columns again to have `utf8mb4` CHARACTER SET and `utf8mb4_unicode_ci` as COLLATE information.

**Comment by rohandaxini** [comment]
@sampatbadhe @SupriyaMedankar 
Finally I was able to fix this issue
We had to also set `encoding` and `collation` in `database.yml` for production.
i.e. following values
```
encoding: utf8mb4
collation: utf8mb4_unicode_ci
```
I just tested emoji's in PROD and works fine now.

Could you please test it in PROD now?

**Comment by rohandaxini** [comment]
@sampatbadhe @SupriyaMedankar 

Finally, I executed  following steps and PROD chores to make "multi byte" characters work in app.
1. Added following mysql configuration in section `[mysqld]` of my.cnf
```
default-storage-engine=InnoDB
innodb_file_format=barracuda
innodb_file_per_table=1
innodb_large_prefix=1
init_connect='SET collation_connection = utf8mb4_unicode_ci'
init_connect='SET NAMES utf8mb4'
character-set-server=utf8mb4
collation-server=utf8mb4_unicode_ci
```

2. Added following mysql configuration in section `[client]` of my.cnf
```
default-character-set = utf8mb4
```

3. Added following mysql configuration in section `[mysql]` of my.cnf
```
default-character-set = utf8mb4
```

4. Restarted mysql server and then ran migrations explicitly for all tables and those required columns.

5. Added following configuration in `database.yml` file for production as
```
encoding: utf8mb4
collation: utf8mb4_unicode_ci
```

6. Restarted knowbuddy app

**Pull request merged**
